### ISSUE TITLE
Copying & Pasting brushes and actors move position in ED

### ISSUE THREAD

**Issue by GamesHarder** [OldUnreal/Unreal-testing#353]
I noticed when CTRL+C & CTRL+V-ing a brush or actor, both the copied and the original brush gets moved to the new position.
This is only when copying with keyboard or right-clicking and Copy Actor and then Paste Actor.

**Comment by Reorn** [comment]
[Issue #321 Last brush/actor Jumping in UnrealEd](https://github.com/OldUnreal/Unreal-testing/issues/321)

**Comment by GamesHarder** [comment]
> [Issue #321 Last brush/actor Jumping in UnrealEd](https://github.com/OldUnreal/Unreal-testing/issues/321)

Ah, sorry. I thought this was something new.
