### ISSUE TITLE
Loading Saved Game Results in Hard Crash (Mac)

### ISSUE THREAD

**Issue by Wooloomooloo2** [OldUnreal/Unreal-testing#359]
Critical Error
Signal: SIGSEGV [segmentation fault]

History: UALAudioSubsystem::PlaySound <- UALAudioSubsystem::Update <- UGameEngine::Draw <- USDLViewport::Repaint <- USDLClient::Tick

This occurs when loading a saved game or quick save after playing. I installed the game using Steam install on Crossover and copying the files to Unreal folder in Application Support per the readme. It all works a treat until you quit and reload or die and load from a save point (respawning is fine).
 
M1 Max, 32GB RAM / Sonoma 14.4.1
<img width="247" alt="Screenshot 2024-04-05 at 9 59 34 AM" src="https://github.com/OldUnreal/Unreal-testing/assets/166140930/96d21d65-65b9-41d7-b3bd-4d4e8773b9bd">

**Comment by stijn-volckaert** [comment]
I think I know what's causing this. We should be able to backport the fix from Unreal Tournament 469

**Comment by stijn-volckaert** [comment]
Could you upload your savegame please? It should be in ~/Library/Application Support/Unreal/Save/

**Comment by Nergus** [comment]
> Critical Error Signal: SIGSEGV [segmentation fault]
> 
> History: UALAudioSubsystem::PlaySound <- UALAudioSubsystem::Update <- UGameEngine::Draw <- USDLViewport::Repaint <- USDLClient::Tick
> 
> This occurs when loading a saved game or quick save after playing. I installed the game using Steam install on Crossover and copying the files to Unreal folder in Application Support per the readme. It all works a treat until you quit and reload or die and load from a save point (respawning is fine).
> 
> M1 Max, 32GB RAM / Sonoma 14.4.1 <img alt="Screenshot 2024-04-05 at 9 59 34 AM" width="247" src="https://private-user-images.githubusercontent.com/166140930/320025948-96d21d65-65b9-41d7-b3bd-4d4e8773b9bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjkxNDMsIm5iZiI6MTcxMjMyODg0MywicGF0aCI6Ii8xNjYxNDA5MzAvMzIwMDI1OTQ4LTk2ZDIxZDY1LTY1YjktNDFkNy1iM2JkLTRkNGU4NzczYjliZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxNDU0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTVlM2JlOTc5ZmI0MmI4MzI3NDhmYzMwMTNmYjIwMTZkZjFhMWY2ZGZhMWI1OWUyNGYzNTk5MGZhNjZjN2UzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1m8fDEtrdsJl84GZft4D0TORoTFUoNVwGQh_8Ebprp0">

I have the same issue but from a GOG copy which I had updated from version 226 to 227i.

**Comment by Wooloomooloo2** [comment]
rename file to .cpgz 
[Save4.usa.tgz](https://github.com/OldUnreal/Unreal-testing/files/14887711/Save4.usa.tgz)

**Comment by Nergus** [comment]
> rename file to .cpgz [Save4.usa.tgz](https://github.com/OldUnreal/Unreal-testing/files/14887711/Save4.usa.tgz)

Where do you place the files ? It doesn't read them if I put them either inside the app or in Application Support/Unreal/Save when renamed to tgz.

**Comment by stijn-volckaert** [comment]
This should be fixed in the new build:
https://github.com/OldUnreal/Unreal-testing/releases/tag/v227k

**Comment by Wooloomooloo2** [comment]
Confirmed, it's fixed. Thank you!

**Comment by Nergus** [comment]
> This should be fixed in the new build: https://github.com/OldUnreal/Unreal-testing/releases/tag/v227k

Seems like most things are fixed on my Apple Silicon, I'll check on Intel but looks great thanks !

**Comment by Nergus** [comment]
> This should be fixed in the new build: https://github.com/OldUnreal/Unreal-testing/releases/tag/v227k

Apple Metal renderer doesn't work on Intel (but it's expected).
Quick loads work when you don't do another quick save on top of the save files you imported to the mac app, but when you do another quicksave, quickload crashes the game, both on Silicon and Intel machines. Manuel saves and loads don't seem to be impacted so that's a good thing.
