### ISSUE TITLE
Return to NaPali with Metal render

### ISSUE THREAD

**Issue by ArekReve** [OldUnreal/Unreal-testing#364]
Addon dasn't start with metal render. With XOpengl render works OK. 
![Zrzut ekranu 2024-04-7 o 10 39 55](https://github.com/OldUnreal/Unreal-testing/assets/25613723/fc9bd3d1-3159-423a-b971-566fb88f0680)

**Comment by stijn-volckaert** [comment]
Confirmed and fixed. I'll upload a new build in a few hours
