### ISSUE TITLE
Deus ex

### ISSUE THREAD

**Issue by do2ggg** [OldUnreal/Unreal-testing#369]
with the help of this patch it is possible to launch Deus ex, or there are plans to add support?

**Comment by uralets** [comment]
Short answer No.

It's not a patch it's a source port, extensively modified from the original Epic code.
DX is a completely different game, and nobody here has the sources for it.

**Comment by MasterO2** [comment]
> with the help of this patch it is possible to launch Deus ex, or there are plans to add support?

@do2ggg, the closest you're gonna get for Deus Ex is https://github.com/dpjudas/SurrealEngine and even that is **preliminary**.
