### ISSUE TITLE
Ultra real time pawn shadows cause framerate drops on Nvidia GPU

### ISSUE THREAD

**Issue by thatspacepirate** [OldUnreal/Unreal-testing#383]
I have an NVIDIA GeForce RTX 4060 Ti. No matter which graphics API I select in Unreal Gold's menu, it always seems to drop frames at random spots. This seems to be caused by the real time pawn shadows setting, as after disabling that it ran smoothly. I was hoping it would run better at full settings on a modern gpu, but I still experienced issues. If you have anything to add or any questions please let me know.

**Comment by metallicafan212** [comment]
This isn't dependant on the GPU or renderer, realtime shadows are done in software on the CPU.

Future improvements to make the shadows utilize the GPu are being explored. Best to stick to medium or lower for now.
