### ISSUE TITLE
Controls Menu is Empty

### ISSUE THREAD

**Issue by TheKins** [OldUnreal/Unreal-testing#386]
Using the current master 1a2d120 64-bit build. No keybinds appear in the Controls menu.

![image](https://github.com/user-attachments/assets/bd75fbfd-cadb-4b17-8a30-2eb576f10f3d)

Witnessed with both the 32-bit and 64-bit builds.

**Comment by metallicafan212** [comment]
Don't use the repo files, use the releases. The repo contents will be cleared in the near future.

https://github.com/OldUnreal/Unreal-testing/releases

**Comment by TheKins** [comment]
I am still seeing a blank Controls window using the latest releases build ([227k_12](https://github.com/OldUnreal/Unreal-testing/releases/tag/v227k_12)). Tested on both a clean reinstall of the Steam version of Unreal Gold, and one with 227j installed.

**Comment by metallicafan212** [comment]
@TheKins Delete your Unreal.ini and User.ini so they regenerate, see if that fixes it.

**Comment by TheKins** [comment]
Still nothing.

**Comment by metallicafan212** [comment]
That's very weird since it's working perfectly for me.... Can you post your Unreal.log, Unreal.ini, and User.ini?
![image](https://github.com/user-attachments/assets/6ef83c6c-2432-4664-88ac-4291ddda20dd)

**Comment by TheKins** [comment]
Sure, but they are, as you advised, the automatically generated versions. The only change I made beyond that was turning off fullscreen mode.

[Unreal.ini.txt](https://github.com/user-attachments/files/18057142/Unreal.ini.txt)
[User.ini.txt](https://github.com/user-attachments/files/18057148/User.ini.txt)
[Unreal.log.txt](https://github.com/user-attachments/files/18057151/Unreal.log.txt)

If it helps diagnose the problem, I am running from an external drive, the startup window was lacking localization information, and neither of these issues are present in 227j.

**Comment by metallicafan212** [comment]
I think you're missing the localization files..... I'll take a better look tomorrow.

Really what I wanted to see is if the inis were generating right.

**Comment by metallicafan212** [comment]
@TheKins try deleting all INT files from both system folders. That way it's pulling them from System Localized

**Comment by TheKins** [comment]
There, that fixed the controls menu! Now we know the cause, at least. I guess something changed from 227k with how System vs SystemLocalized is prioritized?

**Comment by metallicafan212** [comment]
Real quick question, did you use the installer or did you manually patch?

**Comment by TheKins** [comment]
I had the game on Steam from before it was delisted, so I patched that version manually. Does the new standalone installer clean up the INT files as part of its install process?

**Comment by metallicafan212** [comment]
Yes, and the general patch installer should even cleanup steam installs.

**Comment by metallicafan212** [comment]
I'll close this issue now, as the issue was the patch installation. I'll discuss better install steps or maybe keep duplicated INT files to make sure those get replaced.

**Comment by TheKins** [comment]
Hmm. I used the EXE installer for 227j, and still had this issue after applying 227k. Unless the new full game installer also doubles as a patcher for existing releases and I didn't know.

**Comment by metallicafan212** [comment]
The full game installer and patch installer are separate installers.
