### ISSUE TITLE
UnrealEd: The "Undo" and "Redo" buttons stop working after 10-15 minutes of working in the UnrealEd.

### ISSUE THREAD

**Issue by Reorn** [OldUnreal/Unreal-testing#388]
UnrealEd 227k 
The "Undo" and "Redo" buttons and menu items stop working after 10-15 minutes of working in the UnrealEd, and do not work until the end of the session.
If you close and open the editor, its work again.
I can't find any pattern to this.
The previous version (2023-03-28) did not have this bug.

UnrealEd 227k beta (2024-08-28)
Windows 7x64 and Windows 10x64, Different video cards, 
UnrealEd x86 and x64, xOpenGl drv

![Undo](https://github.com/user-attachments/assets/c067083c-a43f-41b3-939f-12c2f3765d19)

**Comment by metallicafan212** [comment]
Update to the latest k build, which came out this month and see if that fixes it.

It's in the releases

**Comment by Reorn** [comment]
As far as I can tell, the bug has been fixed in the latest release (2024-30-11).
I'll test it for another two weeks, if the error doesn't happen again, I'll close this task.
